name: Test Algorithms
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
    - name: Test with pytest
      run: |
        pipenv run python -m pytest
